### ISSUE TITLE
what to do with waiting list now that we dropped invite-only

### ISSUE THREAD

**Issue by guaka** [Trustroots/community#12]
mikael: I have a 11.4 K emails in Maitre on “waiting list” and another ~2K in earlier list in MailChimp. What should we do about those?
they’ve all expressed interest to join, many of them have probably joined.

guaka [10:30 AM]
- exclude emails that have already signed up
- send the remaining emails a message they can now sign up without invite, possibly first try a batch of 100 or so

**Comment by guaka** [comment]
mikael:  wait another week to confirm the upwards trend in signup stats before doing this.

**Comment by simison** [comment]
Upwards trend is there! 💪 

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/87168/47455557-d3241600-d7da-11e8-9c18-db10a1d37525.png">

@guaka let's write an email and send invite to these 11K folks.

**Comment by Lemoert** [comment]
@simison, @guaka - Am guessing we can close this as the issue has been dealt with (?)

**Comment by guaka** [comment]
I'm not sure exactly what happened, I think we sent out mails but I'm not sure.
And even if we didn't send out emails, it may be a bit late now?

@simison?

**Comment by Lemoert** [comment]
Would agree that it's a bit late if we didn't :laughing: Closing issue for now.
