### ISSUE TITLE
Trustroots pic nic Berlin Tuesday 11 August

### ISSUE THREAD

**Issue by guaka** [Trustroots/community#2]
Hi @maikhoepfel @aschle @nikolaygit @florianwittmann @mschwarzer @maltoe!

You're stargazing https://github.com/Trustroots/trustroots and your location is Berlin (or Germany). We're  having a pic nic at Krumme Lanke next Tuesday for which I want to invite you like this.

https://www.facebook.com/events/1446695995658760/1446705102324516/

Let me know if you're not on Facebook and we'll get you the info in another way.

https://www.trustroots.org/#!/profile/guaka
cc @simison 

![image](https://cloud.githubusercontent.com/assets/87168/9152097/9aa59fd0-3e1b-11e5-947d-4de66f577a9e.png)

**Comment by nikolaygit** [comment]
@guaka thank you for the invitation! Currently other priorities here :) Best wishes, nikolay

**Comment by simison** [comment]
Posted event infos here, too: http://ideas.trustroots.org/2015/08/09/trustroots-picnic-berlin/
