### ISSUE TITLE
Polish the Do-ocracy stub on the Wiki and link to it in the newsletter.

### ISSUE THREAD

**Issue by Lemoert** [Trustroots/community#34]

**Comment by guaka** [comment]
https://wiki.trustroots.org/en/Do-ocracy (I like putting links in issues, makes it easier for people to jump right in.)

I just removed `{{stub}}`` because I think it's already a good article. Still plenty room for improvement obviously, and possibly more context.

**Comment by loberto** [comment]
We could maybe add something about how it is to work under this structure.
ie: explaining the difference between "i can do whatever I want" to "I can choose how this thing we discussed is done"

I will try to get a transcript from what Kasper said about this on the Call on the 23rd

**Comment by guaka** [comment]
Great, I just jumped ahead and started a [section: not whatever I want](https://wiki.trustroots.org/en/Do-ocracy#It_doesn.27t_mean:_.22I_can_do_whatever_I_want.22)  - edit the whole article however much as you want ;)
