### ISSUE TITLE
Using GitHub more

### ISSUE THREAD

**Issue by chagai95** [Trustroots/community#48]
1. make guides
2. make videos
3. draft a text to send people explaining we are not a company but a volunteer based organization and therefor would appreciate there help and less their complaints - one way to help would be to just browse around GitHub and add likes to issues or help comment on issues or create issues.
4. using GitHub a place to discuss things more.
5. Add a short overview that some overviews do not have code at all  - add this to the website in volunteering section.

**Comment by Lemoert** [comment]
@chagai95 - Do you reckon we should split this into separate issues and add them to the various active projects?
(Guides are already part of [this project](https://github.com/Trustroots/community/projects/9) while videos could potentially be made a new project or added as a part of that one.)

**Comment by chagai95** [comment]
That'll be great! just added this issue to bring more awarness to these topics

**Comment by Lemoert** [comment]
For now I would suggest we add videos under the HowTo project, and also add point three as a separate issue there. When it comes to point four I think that would be sorted once we write the two GitHub HowTo's ("simple" and "advanced"), while point five would likely go well for when we look into updating the volunteer page etc. Sound good? (I can obviously shift things around, but wanted to check with you first..)

**Comment by chagai95** [comment]
Sounds great!

**Comment by Lemoert** [comment]
1. [Can be found here](https://github.com/Trustroots/community/projects/9).
2. [Converted to this issue](https://github.com/Trustroots/community/issues/85).
3. [Converted to this issue](https://github.com/Trustroots/community/issues/86).
4. Will likely follow after GitHub HowTo's are done.
5. Should be included in the general volunteer information whenever that's written/rewritten.
