### ISSUE TITLE
Sort text layout

### ISSUE THREAD

**Issue by Lemoert** [Trustroots/community#54]
Check the text and change formatting, rainbow separators etc. so it looks good.

**Comment by Lemoert** [comment]
@chagai95 - Do you reckon you could use [the text here](https://trustroots.p2.blog/2020/08/20/updating-the-donate-page/) to create a preview where we can see the layout etc? (You mentioned a GitHub preview option or something like that..)

**Comment by chagai95** [comment]
Sure but I think Nikki was talking about playing around with the design components, you just need to change css and html for that I think and you can just do that from the browser to see how it looks like, I can show you or Nikki if you're interested in that

**Comment by Lemoert** [comment]
Ah, I was more thinking of what format to choose for what text etc. We can have a look at it whenever we have a look at the translation date issue if that sounds good?
