### ISSUE TITLE
Support request: new tribe

### ISSUE THREAD

**Issue by guaka** [Trustroots/community#6]
How do we handle these?

**Comment by simison** [comment]
I already directed them to a google form + spreadsheet:

https://docs.google.com/spreadsheets/d/1w6t6u0KIb4Q43IWRTEk-CW-j_WxFdlUBa5bqYn4YRZs/edit#gid=846590338

...so I think we're good for now. I'm waiting for a volunteer who could help out to skim through a few more suggestions from support mails to that spreadsheet (see 2nd tab in the spreadsheet).

**Comment by guaka** [comment]
Cool, I added a link to the form from https://ideas.trustroots.org/contact/

**Comment by guaka** [comment]
Closing this.
