### ISSUE TITLE
Personal trustroots goals

### ISSUE THREAD

**Issue by guaka** [Trustroots/community#7]
short term:
- [x] get open support requests down to 500 (from 956)
- [x] get overview of trustroots stuff: github, website
- [x] find one person to help with this at least 3 times per week
- [x] non trivial commit to code repo

mid term:
- [ ] build team(s) of volunteers
- [ ] find a way to pay at least 1 salary

**Comment by Lemoert** [comment]
@guaka Seeing as the VA's are working on the first remaining point and the second seems to be quite a long way into the future considering recent discussions on the topic, should we close this?

**Comment by guaka** [comment]
yes!
