### ISSUE TITLE
Trustroots in social media & blogsphere

### ISSUE THREAD

**Issue by guaka** [Trustroots/community#9]
continuation from https://github.com/Trustroots/trustroots/issues/20#issuecomment-393091584

we have:
- [x] [FB page](https://www.facebook.com/trustroots.org)
- [x] [FB group](https://www.facebook.com/groups/trustroots/)
- [x] [Newsletter](http://ideas.trustroots.org/newsletter/)
- [x] [Blog](http://ideas.trustroots.org)
- [x] [Twitter](https://twitter.com/trustroots)
- [x] [VKontakte](https://vk.com/public83461619)
- [x] [Google+ page](https://google.com/+TrustrootsOrg)
- [x] [Google+ group](https://plus.google.com/communities/110376845532540658554)
- [x] [Instagram](https://www.instagram.com/trustroots_org/)

**Comment by danidanitr** [comment]
I'll be taking care of this soon :+1:

**Comment by Lemoert** [comment]
@guaka - This seems all done, okay to close?

**Comment by guaka** [comment]
yes!

I copied the list to README.md
